### PR TITLE
Update links to files with hf.co links

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by julien-c** [comment]
Yes – I'm suspecting that the files that were not migrated were files that were not correctly named (`/`  instead of `-` as a separator for "top-level" model id)

I can do it manually, or would you like to do it yourself? Let me know.

**Comment by guillaume-be** [comment]
> Yes – I'm suspecting that the files that were not migrated were files that were not correctly named (`/` instead of `-` as a separator for "top-level" model id)
> 
> I can do it manually, or would you like to do it yourself? Let me know.

Ok - I will push these 3 files and let you know when it is uploaded. Then the last missing part is a formatting check `rust fmt` and this should allow to trigger the CI again (I migrated over to actions over the week-end, hopefully this switches to the right CI on a new commit)

**Comment by julien-c** [comment]
Feel free to write on top of my PR of course! (you should be able to)

**Comment by julien-c** [comment]
(you might need to rebase for the new CI)

**Comment by guillaume-be** [comment]
Thanks again for the PR!

**Pull request merged**
