### PR TITLE
updated tch-rs to 0.13.0

### PR DESCRIPTION
**Pull request by josephhajduk**
find replaced of_slice to from_slice as per
https://github.com/LaurentMazare/tch-rs/blob/008fff6cc0a91ecff274d1549c2dff25b8ca57a4/CHANGELOG.md

was having trouble running on m1 with 0.12.0,  works with 0.13.0

### CODE REVIEW

**Comment by LaurentMazare** [comment]
A nice addition on 0.13.0 is that the `torch-sys` build script now emits the location of the libtorch shared library via some environment variable, this can be used by top level crates to use some link flags for binaries that remove the need for setting up `LD_LIBRARY_PATH` appropriately. A sample build script that does this would be [diffusers-rs/build.rs](https://github.com/LaurentMazare/diffusers-rs/blob/17a95301b24ab4f30281a2da5b02f44b8dc9393f/build.rs).
(it's a bit sad to need this to be done in the top level crates but afaik there isn't an easy way to set some arbitrary linking flags for the final binaries from the library crates.

Also note that the automated libtorch download is now opt-out, you can get the old behavior with the specific cargo feature though probably better to avoid it if possible.

**Review by guillaume-be — APPROVED** [review]
Thank you @LaurentMazare for the note - these look like good changes indeed and will hopefully make the installation on mac / M1 targets easier. I have copied over the build script from [diffusers-rs/build.rs](https://github.com/LaurentMazare/diffusers-rs/blob/17a95301b24ab4f30281a2da5b02f44b8dc9393f/build.rs), I hope that is fine.

**Comment by diptanu** [comment]
@josephhajduk @guillaume-be This is breaking the build of Indexify -  https://github.com/diptanu/indexify

Any suggestions around how to fix it?

**Comment by josephhajduk** [comment]
I had to explicitly add a direct torch-sys dependency to my project with the download-libtorch feature.  It didn't seem to work by adding the feature to the bert-rs dependency.

**Comment by guillaume-be** [comment]
@diptanu @josephhajduk could you please try to check the branch candidate at https://github.com/guillaume-be/rust-bert/pull/382 without passing `torch-sys` as an additional dependency and let me know if this helps?

**Comment by diptanu** [comment]
@guillaume-be @josephhajduk I responded on the issue - PyO3 broke the build for me, I updated to the new master of rust-bert and added PyO3 which caused the confusion.

I see that new PR has been merged related to the libtorch download feature, will test it soon but I got around to solving the  issue by adding a dependency to tch directly.

**Pull request merged**
