### PR TITLE
update cached-path

### PR DESCRIPTION
**Pull request by epwalsh**
Hey @guillaume-be, I made a few more updates to `cached-path`. See https://github.com/epwalsh/rust-cached-path/releases/tag/v0.4.4 for details.

### CODE REVIEW

**Comment by guillaume-be** [comment]
Hello @epwalsh ,

Thank you for the PR. Progress bars are a rather subjective topic, and I purposely decided not to add them to the file download until now. While some users may like them, they also tend to generate a lot of noise in logs. As you can see in the CI, thousands of lines were generated from the download progress bar.

Could you please add the progress bar to the `Options` you added to `cached-path` (with different progress bar indicator, e.g. full, light, none)? I would then not use the most verbose version from the crate by default, or at least default back to a log-friendly progress indicator (for example adding a `.` to a line every X seconds, ending with `done`, e.g.: `downloading "xxx.ot" to "local/path" ........ done.`. This usually has the advantage of not printing a new line at every step)

I believe at this point I would be happy with just a note saying when a file gets downloaded/refreshed (with possibly very light progress indication) and stay silent when the cache is used.

Would this be an option?
Thanks!

**Comment by epwalsh** [comment]
Yeup, good point about the logs. I remember now that was a pain point in AllenNLP that we handled with a `--file-friendly-logging` configuration option.

**Comment by epwalsh** [comment]
See https://github.com/epwalsh/rust-cached-path/pull/34

**Review by guillaume-be — APPROVED** [review]
Thank you for the PR @epwalsh : I just checked the CI logs and the progress bar plays very nicely!

**Pull request merged**
