### PR TITLE
Additional translation models

### PR DESCRIPTION
**Pull request by guillaume-be**
Addition of multiple translation language pairs:
  - English <-> Mandarin
  - English <-> Cantonese
  - English <-> Dutch
  - English <-> Swedish
  - English <-> Arabic
  - English <-> Hebrew
  - English <-> Hindi

### CODE REVIEW

**Comment by guillaume-be** [comment]
@edwin0cheng It would be great if you could test (either on the Transformers library or with this implementation) the language code that should be implemented to support Chinese languages. So far I attempted to support Mandarin and Cantonese with the prefixes `cmn_Hant` and `yue_Hant` - but another prefix may be better suited. I unfortunately lack the linguistic background to assess the quality of the translation - maybe you could help.

The acceptable prefixes for the `en-zh` models are:
- cjy_Hans 
- cjy_Hant 
- cmn 
- cmn_Hans 
- cmn_Hant 
- gan 
- lzh 
- lzh_Hans 
- nan 
- wuu 
- yue 
- yue_Hans 
- yue_Hant

For some of them the translation quality seemed very poor (tested using backtranslation with other translation tools). The `cmn_Hant` and `yue_Hant` seemed to be the most reasonable in terms of output.

**Comment by edwin0cheng** [comment]
I did a simple test with the following code :

```rust
fn main() -> anyhow::Result<()> {
    let inputs = [
        "Rust is blazingly fast and memory-efficient",
        "with no runtime or garbage collector",
        "it can power performance-critical services",
        "run on embedded devices, and easily integrate with other languages",
    ];
    println!("#### {:?}", MarianPrefix::ENGLISH2CANTONESE);
    translate(&inputs, Language::EnglishToCantonese)?;

    let inputs = [
        "Rust 不僅速度驚人，而且節省記憶體。",
        "由於不需要執行時函式庫或垃圾回收機制，",
        "Rust 可以加速高效能需求的服務",
        "執行在嵌入式裝置，並且輕鬆地與其他語言整合",
    ];

    println!("#### {:?}", MarianPrefix::CHINESE2ENGLISH);
    translate(&inputs, Language::ChineseToEnglish)?;

    Ok(())
}
fn translate(input: &[&str], lang: Language) -> anyhow::Result<()> {
    let translation_config =
        TranslationConfig::new(lang, Device::cuda_if_available());
    let model = TranslationModel::new(translation_config)?;
    let output = model.translate(input);    
    for sentence in output {
        println!("{}", sentence);
    }
    Ok(())
}
```

And the output is quite good in my opinion :
```
#### Some(">>yue_Hant<< ")  <---- Note that it is Hans prefix (Traditional chinese)
 拉斯特速度很快 記憶力也很高
 沒有執行時期或垃圾收集器
 它能發動關鍵性能服務
 在嵌入裝置上執行, 容易與其它語言整合

#### None
 Rust wasn't just fast, he was saving memories.
 Since it is not necessary to run a time library or a garbage recycling system, it is not necessary to do so.
 Rust can speed up the efficient services required.
 Run embedded devices and easily integrate with other languages

#### Some(">>cmn_Hans<< ")   // <---- Note that it is Hans prefix (simplify chinese)
 鲁斯特火速快,记忆力高
 没有运行时间或垃圾收集器
 它能为关键性能的服务提供动力
 在嵌入设备上运行, 并很容易与其他语言整合
```

I am not a chinese linguist, but in general, `Written Chinese` and `Spoken Chinese` maybe very different. For example,  Written Cantonese (I am Cantonese) is very similar to Mandarin one , but one is in Traditional Chinese, another is in Simplified Chinese. 

And another differences are some terms. For example , Computer , in Hong Kong and Taiwan, we called that "電腦" , but in mainland china, is "计算机". 

And other prefixes are very local and the usage are very limited. It is good to support it in the future but I don't think you need it in this stage. 

So,  I would propose the following solution:

Instead of : 
English <-> Mandarin , English <-> Cantonese

Use :
English <-> Traditional Chinese, prefix = `yue_Hant`
English <-> Simplified Chinese,  prefix = `cmn_Hans`

**Comment by guillaume-be** [comment]
Thank you very much @edwin0cheng !
This is very insightful. I have updated the Chinese translation models to Simplified and Traditional instead. Note that I have used for both the `cmn` prefixes as I found it counter-intuitive to switch between Mandarin and Cantonese when switching from Traditional to Simplified. The prefixes used are therefore `cmn_Hant` and `cmn_Hans`.

I hope this makes sense

**Comment by edwin0cheng** [comment]
LGTM. ! 

> I have used for both the cmn prefixes as I found it counter-intuitive to switch between Mandarin and Cantonese when switching from Traditional to Simplified. The prefixes used are therefore cmn_Hant and cmn_Hans.

I think the situation is similar to  Engish(UK) and English(US), e.g. `Waistcoat` and `Vest` are same thing, and its depends where you lives. I think the training set for Cantonese are pull from people in Hong Kong so it will use these terms more frequently.

**Pull request merged**
