### PR TITLE
tiny typo

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by guillaume-be** [comment]
Thank you for the PR. This triggered the build which now fails while downloading and using the `config.json` from[bert-ner]( https://huggingface.co/dbmdz/bert-base-cased-finetuned-conll03-english). This change happened yesterday afternoon (EU timezone)

The `num_labels` field was replaced by `_num_labels`. Is this a design change for the config files?

**Comment by julien-c** [comment]
Pinging @patrickvonplaten on this (also cc @lysandrejik)

In my opinion, we should not even store a `num_labels` on the config, and just write a getter that computes `len(id2label)`

I've cleaned this one config.json manually.

**Comment by guillaume-be** [comment]
Thank you. I am downloading the updated config files and notice that these changes have happened for all models, for several fields which seems to now be optional/clean-up, meaning unfortunately the issue is not limited to this single config file.

I will update this crate configuration parsing and model building in the crate to reflect these changes

**Comment by julien-c** [comment]
Yes. See https://github.com/huggingface/transformers/pull/3797 for more info.

If it's hard to support on your side, we could think about maybe also saving a "full" version of the json as `config_full.json`

**Comment by guillaume-be** [comment]
Thank you for the reference.

Should be fine and preferable to support the new standards on my side. I will include the support for the new config in the upcoming version with native Rust model weights.

**Comment by patrickvonplaten** [comment]
If it helps one can restore the "old" longer config with some python code:
```python
from transformers import AutoConfig
config = AutoConfig.from_pretrained("bert-base-uncased")
config.to_json_file('config_json', use_diff=False)
```

**Comment by guillaume-be** [comment]
@patrickvonplaten @julien-c Thank you for the suggestions and offer to help. I have now updated the code base to be compatible with the new configuration files in the Transformers library (see [#22 ](https://github.com/guillaume-be/rust-bert/pull/22)). Re-running the checks based on this update and merging this PR.

**Pull request merged**
